// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ylbsumyctdjhewcnzyio.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlsYnN1bXljdGRqaGV3Y256eWlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg3NzI4NjIsImV4cCI6MjA1NDM0ODg2Mn0.RjRj0obITVZzFmEkkBinAiJaxpRiXn7DR84RTFU3GNs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);